### ISSUE TITLE
GPU memory allocation issues

### ISSUE THREAD

**Issue by ledochowitsch** [dgreenberg/sbmvivo#2]
Hi David,

I'm trying to run inference on one of your in vivo data segments. Do you have a sense how much GPU memory is needed for that? I am getting the following error message:

> Error using cuda5s_mex_init
> GPU memory allocation failed: error code:

Are there any parameters that I can adjust to trade-off available GPU memory against compute time?

Best,

-Peter

**Comment by dgreenberg** [comment]
Hi Peter,

Did you recompile the cuda mex files using the makefile, or are you using the precompiled versions? Can you tell me what system you're on, what versions Matlab and CUDA you're using, and can you paste the output of the command nvidia-smi here?

Best,
David

**Comment by ledochowitsch** [comment]
Hi David,

In your repository, only sbm_fit contains precompiled mex files, sbm_cuda onIy contains source, so I recompiled the cuda mex files via makefile in that folder. 

I'm on CentOS 7, Matlab2017a, Cuda 9.1; The graphics card in that machine is Cuda compute 3.0 compatible but not particularly beefy (2GB). In nvidia-smi, I can see video memory usage jump up by ~1GB before the error is thrown, so I assume the code requests more memory than available. I am just wondering if you can think of a simple modification to some parameters that would reduce the memory footprint for testing purposes. As requested, please find the nvidia-smi output (at rest) pasted below:

(base) [peterl@ibs-peterl-ux1 Matlab2018]$ nvidia-smi
Thu Dec  6 18:50:36 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 680     Off  | 00000000:01:00.0 N/A |                  N/A |
| 36%   58C    P0    N/A /  N/A |    **704MiB** /  1998MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

For comparison, right before the error:

(base) [peterl@ibs-peterl-ux1 Matlab2018]$ nvidia-smi
Thu Dec  6 18:49:12 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 680     Off  | 00000000:01:00.0 N/A |                  N/A |
| 36%   58C    P0    N/A /  N/A |   **1828MiB** /  1998MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
 
Best,

-Peter

PS: Your paper is very well-written - I enjoyed reading it!

**Comment by dgreenberg** [comment]
Hi Peter,

Thanks for pointing out the missing CUDA mex files, I'll add them shortly.

You might try reducing the number of particles or the filter-smoother window size. The memory usage should scale linearly with (particle count) X (filter smoother window).

Can you verify that the method runs ok when you set the number of particles to 1024?

Glad you liked the paper!
Best,

-David

**Comment by dgreenberg** [comment]
Precompiled mex files have been added for 64 bit linux.

When you first install the repository using `install_sbmvivo.m`, these will be copied to the directory `mex/sbm_cuda`, which will be on the Matlab path, ONLY IF they are not already present. If you've compile them yourself, the compiled version will not be overridden. If you want to revert to the precompiled versions, delete your compiled version and run `install_sbmvivo.m` again.

**Comment by ledochowitsch** [comment]
Hi David,

Thanks for providing the pre-compiled libraries. Unfortunately, they don't run on my machine because there is some GLIBC version (linking?) error. The mex files I compiled earlier seem to work fine, though. 

I slapped a 1080Ti into my tower, and now the memory allocation issue is no more (is looks like your code needs at least 1.2 GB of memory on the GPU with default parameters, and maybe more is requested?). Still a bit confusing, since event the old GPU had > 1.2 GB of free memory.

Anyways, some early feedback: 
I loaded the supplemental data you released, and tried to run sim.infer on a snippet of data as follows:

`[aptimes aptimes_window params opts] = sbm.infer(oerec(2).data(5).f,oerec(2).data(5).frameindex*oerec(2).data(5).info.dwelltimeperimage, 'gcamp6s', params, opts)`

That resulted in an error:

```

Operands to the || and && operators must be convertible to logical scalar values.

Error in profile_likelihood (line 37)
if V.usegpu && (~exist('gpudata','var') || isempty(gpudata))

Error in est_params_temperedmode (line 32)
    [~, ~, ~, params0] = profile_likelihood(f, dt, opts, params0, nA2D, st);

Error in estimate_parameters (line 72)
        [Ppe,prevPpe,prevlikpe] = est_params_temperedmode(Vpe, Ppe, dtpe, Fpe, nA2Dpe);

Error in sbm.run_alg (line 30)
    [P, prevP, prevlik] = estimate_parameters(V, P, dt, F, nA2D);


Error in sbm.infer (line 49)
[M, params, opts] = sbm.run_alg(f, dt, indicator, opts, params, [], [], nA2D);

```

I started the oedatabrowser, and imported the same dataset. I turned on GPU computing, and hit 'Detect'. Neuron 1 seems to have been processed with warnings, but neuron 2 resulted in an error, output is below: 
```
initial MC std.: 1.225863, tempering distribution with temperature 10.000000
Warning: preliminary sampling phase did not complete 
 In aimh_gk (line 160)
  In est_params_temperedmode (line 74)
  In estimate_parameters (line 72)
  In sbm.run_alg (line 30)
  In apdet_sbm (line 25)
  In oedatabrowser>oedatabrowser_detectspikes (line 1396)
  In oedatabrowser>detect_button_Callback (line 1047)
  In gui_mainfcn (line 95)
  In oedatabrowser (line 15)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)oedatabrowser('detect_button_Callback',hObject,eventdata,guidata(hObject)) 

Warning: TM may have produced an insufficent number of samples 
 In aimh_gk (line 166)
  In est_params_temperedmode (line 74)
  In estimate_parameters (line 72)
  In sbm.run_alg (line 30)
  In apdet_sbm (line 25)
  In oedatabrowser>oedatabrowser_detectspikes (line 1396)
  In oedatabrowser>detect_button_Callback (line 1047)
  In gui_mainfcn (line 95)
  In oedatabrowser (line 15)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)oedatabrowser('detect_button_Callback',hObject,eventdata,guidata(hObject)) 



 Final parameter changes:

 gain:             0   ===              0
 zeta:   1.31473e+06   ===    1.31473e+06
 fr  :      0.851726   -->       0.945538  +11%
 S   :        7.3861   -->        15.5984  +111%
 R   :       2.54645   -->        3.40289  +33.6%
 LL at start  log P(F)  -2146.4
 LL at end    log P(F) -2088.76
 Total data length of 36278 exceeds maximum length of 12500, using partial data from 5 segments.
 
 
 initial MC std.: 17.426326, tempering distribution with temperature 55.106880
 Warning: preliminary sampling phase did not complete 

  In aimh_gk (line 160)
   In est_params_temperedmode (line 74)
   In estimate_parameters (line 72)
   In sbm.run_alg (line 30)
   In apdet_sbm (line 25)
   In oedatabrowser>oedatabrowser_detectspikes (line 1396)
   In oedatabrowser>detect_button_Callback (line 1047)
   In gui_mainfcn (line 95)
   In oedatabrowser (line 15)
   In

matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)oedatabrowser('detect_button_Call>back',hObject,eventdata,guidata(hObject)) 
 Error using gmfit_gk (line 14)
 at least five unique samples required
 
 Error in aimh_gk (line 165)
     gstar = gmfit_gk(samples);
 
 Error in est_params_temperedmode (line 74)
 [samples, targetlogpvals, acceptance_ratio, accepted, gstar, extradata, first_update, preliminary_phase_end] = aimh_gk(targetlogpfunc, proposal,
 

 p0, temperature, opts.max_iter_paramest, displayfunc, box_constraints);

 Error in estimate_parameters (line 72)
         [Ppe,prevPpe,prevlikpe] = est_params_temperedmode(Vpe, Ppe, dtpe, Fpe, nA2Dpe);
 
 Error in sbm.run_alg (line 30)
     [P, prevP, prevlik] = estimate_parameters(V, P, dt, F, nA2D);

 
 
 Error in apdet_sbm (line 25)
     [M, P, opts, lik, prevP, stimx, moments, prevlik] = sbm.run_alg(F, dt, indicatorstring, opts, P, [], [], nA2D, []);

 
 Error in oedatabrowser>oedatabrowser_detectspikes (line 1396)
 results = oedb.algfunctions{algind}(oerec, {params}, opts);
 
 Error in oedatabrowser>detect_button_Callback (line 1047)
             oedb = oedatabrowser_detectspikes(oedb, handles, fileinfo, algind, algname, 

 ui.selecteddataset, neuronind); %all segments
 
 Error in gui_mainfcn (line 95)
         feval(varargin{:});
 
 Error in oedatabrowser (line 15)
     gui_mainfcn(gui_State, varargin{:});
 
 Error in
 matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)oedatabrowser('detect_button_Callback',hObject,eventdata,guidata(hObject))
  
 Error while evaluating UIControl Callback.
```
I also tried the 'Train on this dataset' menu option, which resulted in a different error:
```
 Function 'subsindex' is not defined for values of class 'struct'.
 
 Error in oedatabrowser>train_currentds_Callback (line 2515)
         params = oedb.trainfunctions{algind}(oerec([1:(n - 1), n+1:end]), opts); %leave-one-out cross-validation
 
 Error in gui_mainfcn (line 95)
         feval(varargin{:});
 
 Error in oedatabrowser (line 15)
     gui_mainfcn(gui_State, varargin{:});
 
 Error in

 
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)oedatabrowser('train_currentds_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating Menu Callback.
```
Am I doing something stupid?

Please advise.

-Peter

**Comment by dgreenberg** [comment]
Hi Peter,

Please create a separate issue for each problem. This makes it much easier for me to keep track of things, and for other people to chime in on the discussion without reading many previous comments.

Regarding the error "Operands to the || and && operators must be convertible to logical scalar values," it seem you provided a strange (possibly vector) input to options.usegpu, which should be a (scalar) true or false. I'd have to see the options struct you provided to the algorithm to be sure, feel free to save it to a mat file and post it here.

Another issue in the code snippet you posted is that the expression 

`oerec(2).data(5).frameindex*oerec(2).data(5).info.dwelltimeperimage`

will not give the correct image times, as the optional field `dwelltimeperimage` is the time the laser focus stays on the cell in each frame, not the time between frames. What you want is `oerec(2).data(5).t`. This caused the model to fit the data poorly as the time constants were all wrong by a large factor, and the parameter inference algorithm got stuck and wasn't able to generate new metropolis-hasting samples.

The train menu doesn't work yet and should have been disabled. For now see sbm.fit.globalfit() as suggested in the repository's readme.

The warnings and errors you're getting with the GUI are more concerning, I'll look into them before closing this issue.

Best,
David

**Comment by ledochowitsch** [comment]
Hi David, 

Thank you for pointing out what was going wrong with the frame times.

As for options.usegpu, you were correct. Your instructions state:

`To use the GPU, use:

opts.usegpu = 'true';
aptimes = sbm.infer(fluorescence, image_times, indicator, params, opts);
`
which initializes options.usegpu with a string. options.usegpu = 1 solves the problem.

-Peter

**Comment by dgreenberg** [comment]
The remaining issues on this thread have all been addressed by commits in the past 2 weeks. Please open another issue for each specific problem if you encounter any!
Best
David
