### ISSUE TITLE
Warning and error related to number of unique samples

### ISSUE THREAD

**Issue by ledochowitsch** [dgreenberg/sbmvivo#4]
sum.infer throws the following series of warnings and errors:

> Total data length of 20000 exceeds maximum length of 12500, using partial data from 1 segments.

> initial MC std.: 459.202203, tempering distribution with temperature 1452.124869
> Warning: preliminary sampling phase did not complete 
>   In aimh_gk (line 160)
>   In est_params_temperedmode (line 74)
>   In estimate_parameters (line 72)
>   In sbm.run_alg (line 30)
>   In sbm.infer (line 49) 
> Error using gmfit_gk (line 14)
> at least five unique samples required
> 
> Error in aimh_gk (line 165)
>     gstar = gmfit_gk(samples);
> 
> Error in est_params_temperedmode (line 74)
> [samples, targetlogpvals, acceptance_ratio, accepted, gstar, extradata, first_update,
> preliminary_phase_end] = aimh_gk(targetlogpfunc, proposal, p0, temperature,
> opts.max_iter_paramest, displayfunc, box_constraints);
> 
> Error in estimate_parameters (line 72)
>         [Ppe,prevPpe,prevlikpe] = est_params_temperedmode(Vpe, Ppe, dtpe, Fpe, nA2Dpe);
> 
> Error in sbm.run_alg (line 30)
>     [P, prevP, prevlik] = estimate_parameters(V, P, dt, F, nA2D);
> 
> 
> Error in sbm.infer (line 49)
> [M, params, opts] = sbm.run_alg(f, dt, indicator, opts, params, [], [], nA2D);
  
- Can segments with more than 12500 points not be processed?
- What does it mean that the preliminary sampling phase has not been completed?
- Rerunning the same command on the same data several times results in varying numbers of unique_samples, ranging for 1-6 in my hands. Every time the unique number of samples is <5, I get the above error. Please advise.

-Peter

**Comment by dgreenberg** [comment]
Hi Peter,

This info will be added along with the complete documentation. Unfortunately I don't have time to address questions now except for bugs and errors that keep the method from being used.

Segments of any length can be processed, but neuron-specific parameters will be estimated only from at most the first 12500 fluorescence values.

Regarding the number of unique samples, I will address that in issue #2.

Best,
David
